import { requireSession } from "@/lib/auth/session";
import { recommendNextTask } from "@/lib/execution/recommendation";
import type { TaskCandidate } from "@/lib/execution/types";

const tasks: TaskCandidate[] = [
  { id: "positioning", title: "Write your automation-consultant positioning statement", nextAction: "Draft a one-sentence bio naming the SME automation problem you solve.", reason: "A clear problem association makes you easier to discover and recommend.", weeklyRank: 1, estimateMinutes: 45, energy: "medium", focusType: "revenue", status: "todo", shareStatus: "drafting", impact: { revenue: 5, learning: 2, portfolio: 4, automation: 2, enjoyment: 3 } },
  { id: "case-study", title: "Outline the first automation case study", nextAction: "Choose one real workflow and write the problem, intervention, and result headings.", reason: "Businesses trust demonstrated work more than promises; this becomes reusable proof.", weeklyRank: 2, estimateMinutes: 60, energy: "medium", focusType: "portfolio", status: "todo", shareStatus: "ready_to_share", impact: { revenue: 4, learning: 3, portfolio: 5, automation: 4, enjoyment: 4 } },
  { id: "outreach", title: "Create a five-business outreach list", nextAction: "List five businesses where a visible manual workflow could be improved.", reason: "Consistent outreach converts useful proof into real conversations and clients.", weeklyRank: 3, estimateMinutes: 30, energy: "low", focusType: "revenue", status: "todo", shareStatus: "planned", impact: { revenue: 5, learning: 2, portfolio: 2, automation: 2, enjoyment: 3 } },
];

export default async function DashboardPage() {
  await requireSession();
  const next = recommendNextTask(tasks, { availableMinutes: 60, energy: "medium", focus: "revenue" });

  return <main className="min-h-screen bg-[#f5f7f2] text-[#16231e] md:grid md:grid-cols-[236px_1fr]">
    <aside className="hidden min-h-screen flex-col bg-[#163c30] px-5 py-8 text-[#eef5e9] md:flex">
      <a className="mb-14 px-3 text-2xl font-black tracking-[-.12em]" href="/dashboard">E<span className="text-[#d8ef61]">•</span>OS</a>
      <nav className="grid gap-1 text-sm"><a className="rounded-lg bg-white/10 px-3 py-3 font-bold" href="#overview">Overview</a><a className="rounded-lg px-3 py-3 text-[#bbcac0]" href="#week">This week</a><a className="rounded-lg px-3 py-3 text-[#bbcac0]" href="#projects">Projects</a><a className="rounded-lg px-3 py-3 text-[#bbcac0]" href="#opportunities">Opportunities</a></nav>
      <div className="mt-auto border-t border-white/15 px-3 pt-5"><p className="mb-2 text-[10px] font-bold tracking-[.14em] text-[#9db2a5]">OPERATING PRINCIPLE</p><p className="font-serif text-lg leading-tight">Share everything<br />I build.</p></div>
    </aside>
    <section className="mx-auto max-w-6xl px-5 py-9 md:px-14 md:py-12" id="overview">
      <header className="mb-9 flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.14em] text-[#64726b]">EXECUTION OS</p><h1 className="mt-2 font-serif text-4xl tracking-tight md:text-5xl">Make the work visible.</h1></div><button className="rounded-lg border border-[#cad5cb] px-4 py-2 text-sm font-bold text-[#163c30]">Plan with Claude ↗</button></header>
      <section className="mb-6 flex flex-col justify-between gap-5 rounded-2xl bg-[#d8ef61] p-7 lg:flex-row lg:items-end"><div><p className="text-[10px] font-bold tracking-[.14em] text-[#4d5d26]">CURRENT MISSION</p><h2 className="mt-2 font-serif text-3xl tracking-tight">Become the automation consultant SMEs think of first.</h2><p className="mt-3 max-w-2xl text-sm leading-6">Build useful systems, show the work in public, and turn repeated customer problems into owned products.</p></div><p className="text-xs font-bold">Life vision <span className="mx-2 text-[#718138]">→</span> Consulting leads <span className="mx-2 text-[#718138]">→</span> Be easier to discover</p></section>
      <section className="grid gap-6 lg:grid-cols-[1.7fr_.8fr]"><article className="rounded-2xl border border-[#dce4dd] bg-white p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.14em] text-[#64726b]">YOUR NEXT BEST MOVE</p><h2 className="mt-2 font-serif text-2xl tracking-tight">{next?.task.title}</h2></div><span className="rounded-full bg-[#edf0e9] px-3 py-1 text-xs font-bold">{next?.task.estimateMinutes} min</span></div><p className="mt-7 text-sm leading-6"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-[#64726b]">Next action</span>{next?.task.nextAction}</p><div className="mt-5 border-l-[3px] border-[#f0aa72] bg-[#f5f7f2] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#64726b]">Why now</p><p className="mt-1 text-sm leading-6">{next?.explanation}</p></div><div className="mt-6 flex items-center justify-between"><span className="rounded bg-[#eef4d4] px-2 py-1 text-xs font-bold text-[#3d6729]">Revenue focus</span><button className="rounded-lg bg-[#163c30] px-4 py-3 text-sm font-bold text-white">Start task →</button></div></article><article className="flex min-h-56 flex-col rounded-2xl bg-[#163c30] p-7 text-white"><p className="text-[10px] font-bold tracking-[.14em] text-[#aac0b4]">WEEKLY COMMITMENT</p><p className="mt-7 font-serif text-6xl leading-none">0<span className="ml-2 text-sm font-sans text-[#b7c7bf]">/ 3 done</span></p><div className="mt-6 h-1.5 rounded bg-[#416154]" /><p className="mt-4 text-sm text-[#c2d0c8]">Three commitments. One clear direction.</p><a className="mt-auto pt-6 text-sm font-bold text-[#d8ef61]" href="#week">Review this week →</a></article></section>
      <section className="mt-11" id="week"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.14em] text-[#64726b]">THIS WEEK</p><h2 className="mt-2 font-serif text-3xl tracking-tight">Increase your surface area for opportunity.</h2></div><span className="text-xs font-bold text-[#64726b]">3 of 5 priorities</span></div><div className="mt-5 border-t border-[#dce4dd]">{tasks.map((task) => <article className="flex flex-wrap items-center gap-3 border-b border-[#dce4dd] py-4" key={task.id}><span className="w-5 font-mono text-xs text-[#64726b]">0{task.weeklyRank}</span><span className="h-5 w-5 rounded-full border border-[#afbbb2]" /><div className="min-w-48 flex-1"><h3 className="text-sm font-bold">{task.title}</h3><p className="mt-1 text-xs leading-5 text-[#64726b]">{task.reason}</p></div><span className="rounded bg-[#f0f2ed] px-2 py-1 text-xs font-bold capitalize text-[#64726b]">{task.shareStatus.replaceAll("_", " ")}</span><span className="font-mono text-xs text-[#64726b]">{Object.values(task.impact).reduce((a, b) => a + b, 0)}/25</span></article>)}</div></section>
      <section className="mt-11 grid gap-6 md:grid-cols-2" id="projects"><article className="rounded-2xl border border-[#dce4dd] bg-[#edf3e9] p-7"><p className="text-[10px] font-bold tracking-[.14em] text-[#64726b]">ACTIVE PROJECT</p><h2 className="mt-2 font-serif text-2xl">Consulting presence</h2><p className="mt-3 text-sm leading-6 text-[#64726b]">Position the consultancy, create proof of work, and establish a sustainable outreach habit.</p></article><article className="rounded-2xl border border-[#dce4dd] bg-[#fffdf9] p-7" id="opportunities"><p className="text-[10px] font-bold tracking-[.14em] text-[#64726b]">OPPORTUNITY INBOX</p><h2 className="mt-2 font-serif text-2xl">Ideas are safe here.</h2><p className="mt-3 text-sm leading-6 text-[#64726b]">Capture the next AI CRM, WhatsApp bot, or dashboard idea without letting it steal this week.</p><button className="mt-5 text-sm font-bold text-[#163c30]">Capture an opportunity +</button></article></section>
    </section>
  </main>;
}
